var user_mod=require("../model/user");
var express=require('express');
var router=express.Router();

router.post('/',function(req,res,next){
    user_mod.getUsermodLogin(req.body,function(err,rows){
        if(err)
        {
            res.json(err);
        }
        else
        {
            res.json(rows);
        }
    });
});

router.get('/:id?',function(req,res,next){
    if(req.params.id)
    {
        user_mod.getUsermodById(req.params.id,function(err,rows){
            if(err)
            {
                res.json(err);
            }
            else
            {
                res.json(rows);
            }
        });
    }
    else
    {
    user_mod.getAllUsermod(function(err,rows){
        if(err)
        {
            res.json(err);
        }
        else
        {
            res.json(rows);
        }
    });
    }
    });
    router.put('/:id',function(req,res,next){
        user_mod.updateUsermod(req.params.id,req.body,function(err,rows){
            if(err)
            {
                res.json(err);
            }
            else
            {
                res.json(rows);
            }
        });
    });
    router.put('/',function(req,res,next){
        user_mod.updateUserpass(req.body,function(err,rows){
            if(err)
            {
                res.json(err);
            }
            else
            {
                res.json(rows);
            }
        });
    });
module.exports=router;